### PR TITLE
Update text thresholds

### PR DESCRIPTION
**Pull request by cloneofghosts**
## Describe the change
Minor changes to the text thresholds as per https://github.com/Pirate-Weather/pirateweather/issues/152#issuecomment-2508080553

## Type of change

- [x] Bugfixes to existing code
- [ ] Breaking change
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation Updates

## Checklist

- This pull request fixes issue: fixes #
- [ ] Code builds locally. **Your pull request won't be merged unless tests pass**
- [x] Code has been formatted using ruff
- [x] I have signed the CLA agreement

### CODE REVIEW

**Comment by cloneofghosts** [comment]
@alexander0042 I figure you're working on the text summaries at the moment but is this good to merge in? Not a big rush just was wondering if you need me to make some changes.

I also noticed while testing that there were multiple occurrences of pop being 0 while intensity was greater than 0. If it was over 0.02 mm/h then it showed the rain icon.

Maybe we need to check if pop > 0 to show icon/text or if pop is 0 then set intensity to 0 outside of the currently block?

**Comment by alexander0042** [comment]
Love these changes! 
With respect to the POP = 0 thing, I think that probably makes the most sense? Do you know if it's occurring within the NBM domain or outside of it, since it really should be consistent, so I'm curious what source is throwing the difference?

**Review by alexander0042 — APPROVED** [review]

**Comment by alexander0042** [comment]
Ok, added a new version e code and merged this in!

**Comment by cloneofghosts** [comment]
> Love these changes! With respect to the POP = 0 thing, I think that probably makes the most sense? Do you know if it's occurring within the NBM domain or outside of it, since it really should be consistent, so I'm curious what source is throwing the difference?

I see it fairly often when the only models are GFS/GEFS. It may happen in the NBM domain but is much rarer compared to GFS/GEFS.

**Comment by alexander0042** [comment]
Interesting- it technically shouldn't happen, but I'm not surprised that it does. What I suspect is happening comes from [this line in the ingest script](https://github.com/Pirate-Weather/pirate-weather-code/blob/53b2e6c85dfd9dab074dacb5e475632f02c59997/API/GEFS_Local_Ingest.py#L300), where it finds the number of ensembles where there's more than 1 mm of precipitation. So if a couple members have 0<x<0.1 mm of precipitation, then this could happen. 

The best fix is probably to reduce that POP ingest threshold to something closer to 0.05 mm (I picked 0.1 somewhat arbitrarily), as well as add a check in the response script to intensity to zero if POP == 0, probably in the [hourly calculation ](https://github.com/Pirate-Weather/pirate-weather-code/blob/e6f5c5712548d45ab8d9f6e556aa7dc46ca2e380/API/responseLocal.py#L2484) so that the situation doesn't occur where all the hourly blocks say 0 but there's a daily accumulation.

**Pull request merged**
